
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:10 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Versione di MSBuild 17.13.19+0d9f5a35a per .NET Framework
      Compilazione avviata 03/05/2025 17:39:46.
      
      Progetto "D:\\VisualStudio\\repos\\OpenCL_cryptography\\out\\CMakeFiles\\4.0.1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" sul nodo 1 (destinazioni predefinite).
      PrepareForBuild:
        Creazione directory "Debug\\".
        L'output strutturato ├¿ abilitato. La formattazione della diagnostica del compilatore rifletter├á la gerarchia degli errori. Per altri dettagli, vedere https://aka.ms/cpp/structured-output.
        Creazione directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creazione di "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild". ├ê stato specificato "AlwaysCreate".
        Aggiornamento timestamp di "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      VcpkgTripletSelection:
        Using triplet "x64-windows" from "D:\\dev_tool\\vcpkg\\installed\\x64-windows\\"
        Using normalized configuration "Release"
      ClCompile:
        D:\\VisualStudio\\2022\\Community\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX64\\x64\\CL.exe /c /I"D:\\dev_tool\\vcpkg\\installed\\x64-windows\\include" /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        D:\\VisualStudio\\2022\\Community\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:"D:\\dev_tool\\vcpkg\\installed\\x64-windows\\lib" /LIBPATH:"D:\\dev_tool\\vcpkg\\installed\\x64-windows\\lib\\manual-link" kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib "D:\\dev_tool\\vcpkg\\installed\\x64-windows\\lib\\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> D:\\VisualStudio\\repos\\OpenCL_cryptography\\out\\CMakeFiles\\4.0.1\\CompilerIdCXX\\CompilerIdCXX.exe
      AppLocalFromInstalled:
        pwsh.exe -ExecutionPolicy Bypass -noprofile -File "D:\\dev_tool\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "D:\\VisualStudio\\repos\\OpenCL_cryptography\\out\\CMakeFiles\\4.0.1\\CompilerIdCXX\\CompilerIdCXX.exe" "D:\\dev_tool\\vcpkg\\installed\\x64-windows\\bin" "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.write.1u.tlog" "Debug\\vcpkg.applocal.log"
        "pwsh.exe" non ├¿ riconosciuto come comando interno o esterno,
         un programma eseguibile o un file batch.
        Uscita dal comando "pwsh.exe -ExecutionPolicy Bypass -noprofile -File "D:\\dev_tool\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "D:\\VisualStudio\\repos\\OpenCL_cryptography\\out\\CMakeFiles\\4.0.1\\CompilerIdCXX\\CompilerIdCXX.exe" "D:\\dev_tool\\vcpkg\\installed\\x64-windows\\bin" "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.write.1u.tlog" "Debug\\vcpkg.applocal.log"" con codice 9009.
        "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" -ExecutionPolicy Bypass -noprofile -File "D:\\dev_tool\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "D:\\VisualStudio\\repos\\OpenCL_cryptography\\out\\CMakeFiles\\4.0.1\\CompilerIdCXX\\CompilerIdCXX.exe" "D:\\dev_tool\\vcpkg\\installed\\x64-windows\\bin" "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.write.1u.tlog" "Debug\\vcpkg.applocal.log"
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=D:\\VisualStudio\\2022\\Community\\VC\\Tools\\MSVC\\14.43.34808\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Eliminazione del file "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" in corso.
        Aggiornamento timestamp di "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Compilazione progetto "D:\\VisualStudio\\repos\\OpenCL_cryptography\\out\\CMakeFiles\\4.0.1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (destinazioni predefinite) completata.
      
      Compilazione completata.
          Avvisi: 0
          Errori: 0
      
      Tempo trascorso 00:00:01.36
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        D:/VisualStudio/repos/OpenCL_cryptography/out/CMakeFiles/4.0.1/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:83 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:10 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/VisualStudio/repos/OpenCL_cryptography/out/CMakeFiles/CMakeScratch/TryCompile-4wdrgy"
      binary: "D:/VisualStudio/repos/OpenCL_cryptography/out/CMakeFiles/CMakeScratch/TryCompile-4wdrgy"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Ob0 /Od /RTC1"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_MSVC_DEBUG_INFORMATION_FORMAT: "$<IF:$<AND:$<C_COMPILER_ID:MSVC>,$<CXX_COMPILER_ID:MSVC>>,$<$<CONFIG:Debug,RelWithDebInfo>:EditAndContinue>,$<$<CONFIG:Debug,RelWithDebInfo>:ProgramDatabase>>"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/VisualStudio/repos/OpenCL_cryptography/out/CMakeFiles/CMakeScratch/TryCompile-4wdrgy'
        
        Run Build Command(s): D:/VisualStudio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_dd788.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Versione di MSBuild 17.13.19+0d9f5a35a per .NET Framework
        Compilazione avviata 03/05/2025 17:39:47.
        
        Progetto "D:\\VisualStudio\\repos\\OpenCL_cryptography\\out\\CMakeFiles\\CMakeScratch\\TryCompile-4wdrgy\\cmTC_dd788.vcxproj" sul nodo 1 (destinazioni predefinite).
        PrepareForBuild:
          Creazione directory "cmTC_dd788.dir\\Debug\\".
          L'output strutturato ├¿ abilitato. La formattazione della diagnostica del compilatore rifletter├á la gerarchia degli errori. Per altri dettagli, vedere https://aka.ms/cpp/structured-output.
          Creazione directory "D:\\VisualStudio\\repos\\OpenCL_cryptography\\out\\CMakeFiles\\CMakeScratch\\TryCompile-4wdrgy\\Debug\\".
          Creazione directory "cmTC_dd788.dir\\Debug\\cmTC_dd788.tlog\\".
        InitializeBuildStatus:
          Creazione di "cmTC_dd788.dir\\Debug\\cmTC_dd788.tlog\\unsuccessfulbuild". ├ê stato specificato "AlwaysCreate".
          Aggiornamento timestamp di "cmTC_dd788.dir\\Debug\\cmTC_dd788.tlog\\unsuccessfulbuild".
        VcpkgTripletSelection:
          Using triplet "x64-windows" from "D:\\dev_tool\\vcpkg\\installed\\x64-windows\\"
          Using normalized configuration "Debug"
        ClCompile:
          D:\\VisualStudio\\2022\\Community\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX64\\x64\\CL.exe /c /I"D:\\dev_tool\\vcpkg\\installed\\x64-windows\\include" /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_dd788.dir\\Debug\\\\" /Fd"cmTC_dd788.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-4.0\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ Optimizing Compiler versione 19.43.34810 per x64
          Copyright (C) Microsoft Corporation. Tutti i diritti  sono riservati.
          cl /c /I"D:\\dev_tool\\vcpkg\\installed\\x64-windows\\include" /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_dd788.dir\\Debug\\\\" /Fd"cmTC_dd788.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-4.0\\Modules\\CMakeCXXCompilerABI.cpp"
          CMakeCXXCompilerABI.cpp
        Link:
          D:\\VisualStudio\\2022\\Community\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\VisualStudio\\repos\\OpenCL_cryptography\\out\\CMakeFiles\\CMakeScratch\\TryCompile-4wdrgy\\Debug\\cmTC_dd788.exe" /INCREMENTAL /ILK:"cmTC_dd788.dir\\Debug\\cmTC_dd788.ilk" /NOLOGO /LIBPATH:"D:\\dev_tool\\vcpkg\\installed\\x64-windows\\debug\\lib" /LIBPATH:"D:\\dev_tool\\vcpkg\\installed\\x64-windows\\debug\\lib\\manual-link" kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib "D:\\dev_tool\\vcpkg\\installed\\x64-windows\\debug\\lib\\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/VisualStudio/repos/OpenCL_cryptography/out/CMakeFiles/CMakeScratch/TryCompile-4wdrgy/Debug/cmTC_dd788.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/VisualStudio/repos/OpenCL_cryptography/out/CMakeFiles/CMakeScratch/TryCompile-4wdrgy/Debug/cmTC_dd788.lib" /MACHINE:X64  /machine:x64 cmTC_dd788.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_dd788.vcxproj -> D:\\VisualStudio\\repos\\OpenCL_cryptography\\out\\CMakeFiles\\CMakeScratch\\TryCompile-4wdrgy\\Debug\\cmTC_dd788.exe
        AppLocalFromInstalled:
          pwsh.exe -ExecutionPolicy Bypass -noprofile -File "D:\\dev_tool\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "D:\\VisualStudio\\repos\\OpenCL_cryptography\\out\\CMakeFiles\\CMakeScratch\\TryCompile-4wdrgy\\Debug\\cmTC_dd788.exe" "D:\\dev_tool\\vcpkg\\installed\\x64-windows\\debug\\bin" "cmTC_dd788.dir\\Debug\\cmTC_dd788.tlog\\cmTC_dd788.write.1u.tlog" "cmTC_dd788.dir\\Debug\\vcpkg.applocal.log"
          "pwsh.exe" non ├¿ riconosciuto come comando interno o esterno,
           un programma eseguibile o un file batch.
          Uscita dal comando "pwsh.exe -ExecutionPolicy Bypass -noprofile -File "D:\\dev_tool\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "D:\\VisualStudio\\repos\\OpenCL_cryptography\\out\\CMakeFiles\\CMakeScratch\\TryCompile-4wdrgy\\Debug\\cmTC_dd788.exe" "D:\\dev_tool\\vcpkg\\installed\\x64-windows\\debug\\bin" "cmTC_dd788.dir\\Debug\\cmTC_dd788.tlog\\cmTC_dd788.write.1u.tlog" "cmTC_dd788.dir\\Debug\\vcpkg.applocal.log"" con codice 9009.
          "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" -ExecutionPolicy Bypass -noprofile -File "D:\\dev_tool\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "D:\\VisualStudio\\repos\\OpenCL_cryptography\\out\\CMakeFiles\\CMakeScratch\\TryCompile-4wdrgy\\Debug\\cmTC_dd788.exe" "D:\\dev_tool\\vcpkg\\installed\\x64-windows\\debug\\bin" "cmTC_dd788.dir\\Debug\\cmTC_dd788.tlog\\cmTC_dd788.write.1u.tlog" "cmTC_dd788.dir\\Debug\\vcpkg.applocal.log"
        FinalizeBuildStatus:
          Eliminazione del file "cmTC_dd788.dir\\Debug\\cmTC_dd788.tlog\\unsuccessfulbuild" in corso.
          Aggiornamento timestamp di "cmTC_dd788.dir\\Debug\\cmTC_dd788.tlog\\cmTC_dd788.lastbuildstate".
        Compilazione progetto "D:\\VisualStudio\\repos\\OpenCL_cryptography\\out\\CMakeFiles\\CMakeScratch\\TryCompile-4wdrgy\\cmTC_dd788.vcxproj" (destinazioni predefinite) completata.
        
        Compilazione completata.
            Avvisi: 0
            Errori: 0
        
        Tempo trascorso 00:00:01.35
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:227 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:10 (project)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'CXX': D:/VisualStudio/2022/Community/VC/Tools/MSVC/14.43.34808/bin/HostX64/x64/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/Internal/CMakeDetermineLinkerId.cmake:36 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:264 (cmake_determine_linker_id)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:10 (project)"
    message: |
      Running the CXX compiler's linker: "D:/VisualStudio/2022/Community/VC/Tools/MSVC/14.43.34808/bin/HostX64/x64/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.43.34810.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
...
